import {
	Binary,
	Braces,
	CalendarRange,
	Clock,
	Code2,
	Database,
	Eye,
	FileCode,
	FileJson,
	FileText,
	GitCompare,
	Hash,
	Image,
	Key,
	Link,
	type LucideIcon,
	Palette,
	QrCode,
	Shield,
	Terminal,
} from 'lucide-react'

export type ToolMetadata = {
	id: string
	name: string
	description: string
	category: 'Converters' | 'Formatters & Parsers' | 'Dev Utilities'
	icon: LucideIcon
	tags: string[]
}

export const TOOLS: ToolMetadata[] = [
	{
		id: 'unix-converter',
		name: 'Unix Epoch Clock',
		description: 'Convert epoch timestamps to human-readable dates and vice versa.',
		category: 'Converters',
		icon: Clock,
		tags: ['epoch', 'timestamp', 'date', 'time', 'unix', 'millis'],
	},
	{
		id: 'json-formatter',
		name: 'JSON Formatter & Validator',
		description: 'Beautify, minify, and validate JSON data with syntax highlighting.',
		category: 'Formatters & Parsers',
		icon: Braces,
		tags: ['json', 'format', 'beautify', 'minify', 'validate', 'lint', 'prettify'],
	},
	{
		id: 'javascript-formatter',
		name: 'JavaScript Formatter/Minifier',
		description: 'Format, beautify, and minify JavaScript code blocks with customized indentation.',
		category: 'Formatters & Parsers',
		icon: Code2,
		tags: ['javascript', 'js', 'format', 'minify', 'beautify', 'prettify'],
	},
	{
		id: 'base64-string',
		name: 'Base64 Text Codec',
		description: 'Safely encode and decode text strings to and from Base64 format.',
		category: 'Converters',
		icon: Binary,
		tags: ['base64', 'encode', 'decode', 'string', 'text', 'binary'],
	},
	{
		id: 'base64-image',
		name: 'Base64 Image Codec',
		description: 'Convert images to Base64 data URIs or decode Base64 strings to images.',
		category: 'Converters',
		icon: Image,
		tags: ['base64', 'image', 'encode', 'decode', 'file', 'drag', 'drop', 'png', 'jpg'],
	},
	{
		id: 'regex-tester',
		name: 'Regex Parser & Tester',
		description: 'Test Javascript regular expressions with color-coded group matches in real-time.',
		category: 'Dev Utilities',
		icon: Code2,
		tags: ['regex', 'regexp', 'test', 'match', 'pattern', 'expression', 'groups'],
	},
	{
		id: 'url-encoder',
		name: 'URL Encoder & Decoder',
		description: 'Safely encode and decode URI components/parameters.',
		category: 'Converters',
		icon: Link,
		tags: ['url', 'uri', 'encode', 'decode', 'percent', 'escape'],
	},
	{
		id: 'html-encoder',
		name: 'HTML Entity Encoder/Decoder',
		description: 'Convert characters to their corresponding HTML entities and vice-versa.',
		category: 'Converters',
		icon: FileCode,
		tags: ['html', 'entities', 'encode', 'decode', 'escape', 'unescape', 'sanitize'],
	},
	{
		id: 'html-preview',
		name: 'HTML Sandbox (Live Preview)',
		description: 'Render and preview raw HTML/CSS/JS in a secured sandboxed iframe.',
		category: 'Dev Utilities',
		icon: Eye,
		tags: ['html', 'preview', 'render', 'sandbox', 'iframe', 'live', 'page'],
	},
	{
		id: 'markdown-preview',
		name: 'Markdown Playground',
		description: 'Compile and render Rich Markdown content to HTML on the fly.',
		category: 'Dev Utilities',
		icon: FileText,
		tags: ['markdown', 'md', 'preview', 'render', 'html', 'marked'],
	},
	{
		id: 'diff-checker',
		name: 'Text Diff Checker',
		description:
			'Compare two text snippets and see highlighted differences side-by-side or inline.',
		category: 'Dev Utilities',
		icon: GitCompare,
		tags: ['diff', 'compare', 'text', 'merge', 'changes', 'patch'],
	},
	{
		id: 'cron-parser',
		name: 'Cron Schedule Parser',
		description: 'Decode cron expressions into human-readable text and predict next run times.',
		category: 'Formatters & Parsers',
		icon: CalendarRange,
		tags: ['cron', 'schedule', 'tab', 'parse', 'interval', 'job', 'timer'],
	},
	{
		id: 'color-studio',
		name: 'Color Studio (Converter/Picker)',
		description:
			'Convert color formats (HEX, RGB, HSL, CMYK) and pick colors from your screen or image files.',
		category: 'Converters',
		icon: Palette,
		tags: ['color', 'hex', 'rgb', 'hsl', 'cmyk', 'picker', 'convert', 'palette', 'eyedropper'],
	},
	{
		id: 'curl-to-code',
		name: 'cURL Request Compiler',
		description:
			'Transform client cURL command strings into Fetch API, Python, or Go request blocks.',
		category: 'Converters',
		icon: Terminal,
		tags: ['curl', 'fetch', 'python', 'go', 'request', 'code', 'generate', 'api'],
	},
	{
		id: 'json-to-code',
		name: 'JSON to Types/Go Code',
		description: 'Parse raw JSON structures and auto-generate clean TypeScript interfaces.',
		category: 'Converters',
		icon: FileJson,
		tags: ['json', 'typescript', 'ts', 'interface', 'type', 'convert', 'model'],
	},
	{
		id: 'mock-generator',
		name: 'Data Forge (Mock Data Gen)',
		description: 'Generate high-quality mock data datasets (JSON) using customizable schemas.',
		category: 'Dev Utilities',
		icon: Database,
		tags: ['mock', 'data', 'forge', 'json', 'generate', 'schema', 'faker', 'test'],
	},
	{
		id: 'uuid-generator',
		name: 'UUID Generator',
		description: 'Bulk generate RFC 4122 compliant UUID v1 or v4 unique identifiers.',
		category: 'Dev Utilities',
		icon: Hash,
		tags: ['uuid', 'guid', 'id', 'generate', 'random', 'key'],
	},
	{
		id: 'password-generator',
		name: 'Password Generator',
		description: 'Create cryptographically secure random passwords with custom parameters.',
		category: 'Dev Utilities',
		icon: Key,
		tags: ['password', 'generator', 'security', 'random', 'credentials', 'entropy'],
	},
	{
		id: 'qr-code',
		name: 'QR Code Studio (Gen/Scan)',
		description: 'Generate pixel-perfect QR codes and decode QR scanner images client-side.',
		category: 'Dev Utilities',
		icon: QrCode,
		tags: ['qrcode', 'qr', 'barcode', 'generate', 'scan', 'read', 'decode'],
	},
	{
		id: 'favicon-generator',
		name: 'Favicon Maker',
		description: 'Generate standard multi-size favicon.ico packages from images, emojis, or text.',
		category: 'Converters',
		icon: Image,
		tags: ['favicon', 'ico', 'icon', 'png', 'emoji', 'text', 'convert'],
	},
	{
		id: 'jwt-codec',
		name: 'JWT Decoder & Encoder',
		description: 'Decode, encode, sign and analyze JSON Web Tokens (JWT) client-side in real-time.',
		category: 'Formatters & Parsers',
		icon: Shield,
		tags: ['jwt', 'token', 'decode', 'encode', 'json', 'sign', 'signature'],
	},
	{
		id: 'text-analyzer',
		name: 'Text Analyzer',
		description:
			'Analyze text statistics (word count, density) and convert string cases on the fly.',
		category: 'Formatters & Parsers',
		icon: FileText,
		tags: ['text', 'case', 'stats', 'wordcount', 'lowercase', 'uppercase', 'camelcase'],
	},
]
